name: Main workflow
on: push
jobs:
    Build:
        runs-on: ubuntu-latest
        container: gradle:6.8.3-jdk11
        steps:
            - name: Clone down the repository
              uses: actions/checkout@v2
            - run: ci/build-app.sh
            